### ISSUE TITLE
Call from jQuery

### ISSUE THREAD

**Issue by sunilbhatia21** [nbuytaert1/apex-alertify#4]
Hi Nick,

I am trying to use plugin https://apex.world/ords/f?p=100:710:30717329629257::::P710_PLG_ID:BE.CTB.ALERTIFY . It is working fine when used from dynamic action. 

Can you please let me know how can i call and use the same from specific jQuery function?

Thanks
Sunil Bhatia

**Comment by nbuytaert1** [comment]
Hello Sunil,

The Alertify APEX plugin is not based on a jQuery plugin. Alertify is nothing more than a plain JavaScript plugin. It is possible to use Alertify without having to create dynamic actions in APEX. You'll just have to make sure that your page includes the proper JavaScript and CSS files for Alertify.

If your page already includes an Alertify dynamic action, then it is not necessary to manually add the JavaScript and CSS files yourself. More information on how to include these files can be found on the Alertify website, under the _Setup_ and _Usage_ sections: http://fabien-d.github.io/alertify.js/

After the files have been included on your page, you can start using Alertify in a very simple way. Go through the _Default Usage_ section of the above website to familiarize yourself with the Alertify API.

The following line for example shows a success notification:
`alertify.success("Success notification");`

Hope that helps,
Nick

**Comment by sunilbhatia21** [comment]
Hi Nick.

Thanks a lot. This is working fine now

Regards,
Sunil Bhatia
